### ISSUE TITLE
Ignore genes with very low experssion

### ISSUE THREAD

**Issue by ms-gx** [VingronLab/APL#6]
Excellent algorithm and tool!

Is there a way to exclude genes with very low expression from the analysis on stage of APL? Or does this not work with the algorithm or does not make sense?

Ideally the genes are excluded from the "top" genes (cacomp). Or an different stage.

I want to do this when running APL. I do not want to exclude those genes before in Seurat.

My aim is to reduce run time and memory requirements.

**Comment by ClemensKohl** [comment]
Thanks for the feedback!

If I understand you correctly you would like to remove genes that are lowly expressed _after_ performing correspondence analysis? Or do you mean you would like to remove them before CA, at the same time or before the genes with the highest inertia are chosen?

If you plan to remove the genes after CA, this would be doable, but we decided against it in order to avoid confusion about the validity of the CA results. As the CA coordinates would change if you started out with less genes, removing them after CA might lead to unanticipated results. That being said, if you only want to remove the genes for e.g. visualization purposes and are aware of the fact that the computed coordinates are strictly speaking only valid for the count matrix originally submitted to CA, I can give you a method for subsetting the cacomp object at any time.

If you would like to do it before running cacomp, we do not currently have a specific method implemented to filter out lowly expressed genes. Although I expect you could very easily write a one-liner filtering out genes when running cacomp, similar to
`ca <- cacomp(obj = count_mat[(rowSums(count_mat > 0) > (ncol(count_mat)*0.01)),]
`
which would filter out genes expressed in <1% of the cells. For a more sophisticated approach (e.g. taking clustering information into account) you might have to write a helper function.

**Comment by ms-gx** [comment]
Dear Clemens
That is what I wanted, at least for a start. I was not sure if I could just filter `count_mat`  without having checked details of your implementation. Thanks for giving an example!

Thank you so much, I'll come back to you if I need a more fine grained/improved filtering.

To answer your question: It depended a bit on the run. The memory bottleneck happened both at scoring and `cacomp` sometimes. But my aim was also to speed up things since I could have added more memory.

**Comment by ms-gx** [comment]
I some filtering might be relevant for other people. Closing the issue for now.
